### ISSUE TITLE
Is Sodium Incompatible, as shown in versions tab

### ISSUE THREAD

**Issue by ghost** [StartsMercury/simply-no-shading#125] opened 2024-10-16 10:14 UTC
I use this mod daily and I haven't seen any breakage while playing with Sodium

**Comment by StartsMercury** [comment] 2024-10-16 10:59
> I use this mod daily and I haven't seen any breakage while playing with Sodium

May I know the version of Minecraft, Simply No Shading, and Sodium?

There are new version 0.6.0 beta versions of Sodium for 1.21(.1) and Simply No Shading 7.5.0 (or later) requires that version of Sodium or later. Unfortunately, I am not planning to support older versions of sodium on the same Minecraft versions.

If you think this is a mistake, such as this mod requiring newer version of Sodium on an older version of Minecraft, please do tell! Thank you.

**Comment by StartsMercury** [comment] 2024-10-17 05:58
I can see what you mean now! Yeah, this is partially incorrect and partially caused by my auto-release set-up.

![image](https://github.com/user-attachments/assets/0bec3d1e-e290-43c4-ae07-d8a1f7b2002a)

**Comment by StartsMercury** [comment] 2024-10-17 06:09
Should be fixed on Modrinth now.

**Closed as completed by StartsMercury** 2024-10-17 06:09 UTC
Labels: bug
